### PR TITLE
add-spanish-translation

### PR DESCRIPTION
**Pull request by quiqueciria**
Hello,

This is the first time that I contribute to a repository in GitHub. I’m
sorry if it isn’t the right way.

I like the Trello Super Power and is a pleasure for me to contribute.

Good job!

### CODE REVIEW

**Comment by christiankaindl** [comment]
This is the first time for me as well, thank you so much for contributing! The new translations will go out with the next release hopefully somewhere in the coming two weeks :)

**Comment by christiankaindl** [comment]
Things going out soon, only thing missing is updating French translations for the new user interface (that comes with the next update). Have to wait for a friend there...

Just a question: Have you used the [CONTRIBUTE.md](https://github.com/christiankaindl/trello-super-powers/blob/master/CONTRIBUTE.md) guide to help with the translations? If yes, how helpful was it? Would be interesting what your experience was so it can be improved in the future :)

**Comment by quiqueciria** [comment]
Hi Christian,

It was super useful. `contribute.md` helped me enought for understand it all. Also, I have say that I just payed attetion to the part of _Translations_, but I didn't any problem for make to colaborate.

All very well explained :)

**Comment by christiankaindl** [comment]
The new version with the Spanish translations is already out.

Roughly 50 people can now use TSP in their native language, thanks to your contribution. For more information on the 0.9 release, read here: https://listed.standardnotes.org/@christiankaindl/1064/trello-super-powers-add-on-v0-9-release-notes

Thank you so much!

**Pull request merged**
